networks:
  video_generation:
    external: true
    name: Video Generation
services:
  instagram-reels:
    build: .
    networks:
      video_generation:
        ipv4_address: 10.20.0.12
    ports:
    - 8769:8048
    restart: unless-stopped
    volumes:
    - instagram-uploader_instagram-reels_sounds:/app/sounds
version: '3.8'
volumes:
  instagram-uploader_instagram-reels_sounds:
    name: instagram-uploader_instagram-reels_sounds
