version: '3.8'
services:
  instagram-reels:
    build: .
    ports:
      - "8769:8048"
    volumes:
      - ./config:/app/config
      - ./sounds:/app/sounds
    restart: unless-stopped
    networks:
      video_generation:
        ipv4_address: 172.20.0.12  # Different IP from previous services

networks:
  video_generation:
    external: true
    name: "Video Generation"
